server:
  port: 8092
spring:
  application:
    name: comment-service
  profiles:
    include: env
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view: false
  cloud:
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
logging:
  level:
    p6spy: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
